version: '3.8'

services:
  web_service:
    container_name: web-service
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8000:8000'
    environment:
      NODE_ENV: production
      PORT: 8000
      API_PREFIX: api/v1
      APP_NAME: Tourist Destination Lumina API
      APP_VERSION: 1.0.0
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_MOTOR: postgres
      DB_NAME: el_salvador_dev
      DB_USERNAME: develop
      DB_PASSWORD: 'dev$123'
